### ISSUE TITLE
[terra-menu] Add new features (header, optgroup titles, icons)

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-framework#474]
# Feature Request

## Description
From #1849:
- [ ] ability to add a grouping/section sub-header titles, similar to [OptionGroups](https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/_OptGroup.jsx)

#

From #1864:
When bounded, Menu renders header text within the back button. So, the click target is the back button + header text. It is now expected for the click target to only encompass the back button.

#### Potential Solution
- [ ] Render back button with `fitStart`
- [ ] Render header text with `fill`

#

Additional new features & adjustments:
- [ ] ability to add an icon before a menu item (other than checkmark which is existing) 
- [x] ~~ability to add "Electronic Instructions For Use" icon before a menu item first class (Moved to #818)~~
- [x] ~~add a mandatory top header with a title for any menu that has a drill-in nested menu on the first-tier of the menu (currently only adds the header on the second-tier and higher). Fixed on #977~~
- [ ] spike on markup structure to factor and best match construction with theme designs (separate, non-overlapping background areas for the header, menu-body)
- [ ] either refactor top header(and submenu nested menu headers) so the height will flex based on title content and correctly wrap, or import action-header which already has intended layout.
- [ ] menu content gets focus glow in Chrome when focus trapped (noticeable when zoomed in) so may need to add extra focus styling (or remove outline) for the outer menu container when automatically put in focus as menu opens.
- [ ] need to refactor the disabled menu-item so the themable opacity can apply to the entire list-item (icons/text/and chevrons), and then themeable individual colors for the icons/text/chevrons.
- [ ] Ability to define the menu attachment behavior (center, and left-to-right, in addition to the current right-to-left) #473

#

**Comment by yuderekyu** [comment]
### Issues moved to framework
Action header issue - https://github.com/cerner/terra-framework/issues/476
Hotkeys issue - https://github.com/cerner/terra-framework/issues/475

**Comment by hboege** [comment]
@ryanthemanuel you have closed this issue, but what happens to all the items under "Additional new features & adjustments"?  Only 1 has been marked completed.  Have they been relocated to other issues?

**Comment by ryanthemanuel** [comment]
@hboege good catch.  Reopening

**Comment by neilpfeiffer** [comment]
Need to re-examine the points listed above if any Design Standard requirements aren't missing and examine the UX Audit: 
https://github.com/cerner/terra-framework/issues/1297

Should also pair with a fix for resizing and submenus:
https://github.com/cerner/terra-framework/issues/952
